# Generated by Django 2.2.3 on 2019-07-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='用户名')),
                ('money', models.FloatField(blank=True, default=0, null=True, verbose_name='变动之前余额')),
                ('pay_name', models.CharField(default='', max_length=128, verbose_name='利息账户')),
                ('program_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='项目名称')),
                ('program_minPay', models.IntegerField(blank=True, null=True, verbose_name='最小买入值')),
                ('program_payBack', models.FloatField(blank=True, null=True, verbose_name='利率%')),
                ('payDay', models.IntegerField(blank=True, null=True, verbose_name='周期（天）')),
                ('program_count', models.IntegerField(blank=True, null=True, verbose_name='买入数量')),
                ('mone_done', models.FloatField(blank=True, default=0, null=True, verbose_name='变动之后余额')),
                ('payMoney', models.FloatField(blank=True, default=0, null=True, verbose_name='应该获得的利润')),
                ('c_time', models.DateTimeField(auto_now=True, null=True, verbose_name='发生时间')),
                ('out_time', models.DateTimeField(blank=True, null=True, verbose_name='获得利息时间')),
            ],
            options={
                'verbose_name': '变更记录',
                'verbose_name_plural': '变更记录',
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='ProgramInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='项目名称')),
                ('programText', models.TextField(verbose_name='项目简介')),
                ('minPay', models.IntegerField(verbose_name='最小买入值')),
                ('payBack', models.FloatField(verbose_name='利率%')),
                ('payDay', models.IntegerField(verbose_name='周期（天）')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创立时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目名称',
                'ordering': ['c_time'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('money', models.FloatField(default=0, verbose_name='用户余额')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('realName', models.CharField(default='', max_length=128, verbose_name='真实姓名')),
                ('bank', models.CharField(default='', max_length=128, verbose_name='银行')),
                ('bank_details', models.CharField(default='', max_length=256, verbose_name='开户行')),
                ('bank_acount', models.CharField(default='', max_length=256, verbose_name='卡号')),
                ('pay_name', models.CharField(default='', max_length=128, verbose_name='利息账户')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['c_time'],
            },
        ),
    ]
